### ISSUE TITLE
Publish/sync directories to IPFS via Textile

### ISSUE THREAD

**Issue by balupton** [textileio/meta#15]
Specific use cases below.

## Static Website Publishing

Each deployment gets a hash, and deployment labels can be assigned such as `production` and `development` to specific hashes. Labels can be via IPNS or DNS-Link.

> @balupton: would use this today

## Directory Sync
Say you have a media feed (e.g. instagram), it would be nice if you could tell textile to sync it with a local directory so your data is readily available on your file system. Or new files that you add are publishing up.

> @balupton: seems a good desktop app would supersede this desire, however one-way sync may be a better idea here for this feature. So you could make say a "Upload to my Photo Feed" folder, and any files dumped in that get published then deleted. Or a "Downloads from my Photo Feed" folder, which is read only except for textile which dumps everything from the thread into it.

**Comment by sanderpick** [comment]
related: https://github.com/textileio/go-textile/issues/612

**Comment by carsonfarmer** [comment]
Closing this as no longer relevant/could be done via Threads V2 approach
