### ISSUE TITLE
Multi schema threads

### ISSUE THREAD

**Issue by advatar** [textileio/meta#16]
Often in chat like apps you need to exchange data adhering to different schema. How can this be handled?

At the moment I maintain an array of threads per chat, each with different schema like media, location, bookmark, healthkit data etc

Alternatives would be

1. Use one schema to rule them all and make everything optional
2. Make use of a directory structure where each thread can have a number of subthreads

Don't know what is best here?

**Comment by sanderpick** [comment]
I think the ability to make a schema node optional is really powerful. I'm gearing up to take another stab at schemas. I can include this as well as https://github.com/textileio/go-textile/issues/612, which together should solve your usecase.

**Comment by carsonfarmer** [comment]
Closing this in favor of threads V2, in which hard schemas are no longer required. Please track progress here: https://github.com/textileio/go-textile-threads
