### ISSUE TITLE
Add why and what inline documentation to the code

### ISSUE THREAD

**Issue by balupton** [textileio/meta#20]
This issue is under the school of thought that one should be able to quickly skim only the comments of a codebase to understand what it is doing and why, at greater speed and comprehension of intent than what reading the code alone offers.

As I brain parse the different parts of the codebase, I'll document in the form of line docs my learnings, and this will help reduce the time for future people to grok the codebase with their own brains. Which will make debugging and onboarding easier.

**Comment by balupton** [comment]
Started doing this yesterday while I track down the execution flow for why gateway configuration is empty for the tests.

**Comment by carsonfarmer** [comment]
Closing this as 'no longer relevant/a priority'.
