### ISSUE TITLE
Add tutorial for Textile based Electron app releases

### ISSUE THREAD

**Issue by andrewxhill** [textileio/meta#22]
Some people asking for it so wanted to get this documented. I'm thinking of documenting the release with 3 options of increasing difficulty.

1. 2 liner. Build locally and use ghr to push releases to your github repo.
2. Expand that and show how to add it as a script in your `package.json`
3. Show how to use it in CircleCI  (https://github.com/textileio/photos-desktop/blob/master/.circleci/config.yml)

**Comment by andrewxhill** [comment]
I went through the last one briefly and tried to think of the steps. Just saving this here,

### Circle CI steps.

1. Create a CircleCI account

- See reference here, https://circleci.com/docs/2.0/configuration-reference/
- You'll want to use CicleCI config versions 2.x

Optional. Setup Mac builds.

- We run our Mac builds using the CircleCI Mac instances. This is an add-on to the normal account
- Alternatively, you can build mac releases locally and push them manually using ghr.

2. Get your GitHub token. You'll need to keep this secure, don't post it anywhere and follow the CircleCI instructions carefully.

- See reference here, https://circleci.com/docs/2.0/gh-bb-integration/
- You don't have to create a machine user but we do and it works well. 

3. Setup your CicleCI with Github details

- See here, https://circleci.com/blog/publishing-to-github-releases-via-circleci/
- Specifically, you need the environmental variables to run ghr
- The ghr tool is used to push releases back to your gihub page after they are built

3. Use the Textile React app CircleCI setting

- Only Mac so far https://github.com/textileio/photos-desktop/blob/master/.circleci/config.yml

**Comment by leshokunin** [comment]
@andrewxhill @carsonfarmer is this up to date? Could you help us, we’re about to tackle this.
