### ISSUE TITLE
Order more hex stickers for barcelona

### ISSUE THREAD

**Issue by andrewxhill** [textileio/meta#27]
@sanderpick if the stickers came out nice, or just need a tweak, can you order another big batch and ship them to mine? ideally enough for that event plus sharing with benjamin and carson to take for future events.

**Comment by sanderpick** [comment]
Like 500?

**Comment by andrewxhill** [comment]
sgtm

**Comment by sanderpick** [comment]
Cool, done.

Here's the full res so that it's online somewhere: 

https://s3.amazonaws.com/textile.public/hex_f.png

Also sent some of these to your address:

https://s3.amazonaws.com/textile.public/letters.png

**Comment by sanderpick** [comment]
The lettering one is a clear style (no white background).
