### ISSUE TITLE
IPFS Camp workshop ideas

### ISSUE THREAD

**Issue by andrewxhill** [textileio/meta#28]
I think [the latest idea](https://textileio.slack.com/archives/C4SRZCPEY/p1557808072034800?thread_ts=1557793416.031200&cid=C4SRZCPEY) from @balupton is the strongest,

> this is textile, this is how it works, here are the concepts behind it, there are threads, this is how you create your own thread.
> 
> It could be delivered via ground up as described - or from the top down, so have a recipe, then work back to its connector, then work back to its api calls, then work back to its threads, then work back to the concepts, etc.
> 
> So I think a focus on threads is probably the best option. Also, we want to leverage their expertise too.
> 
> Mounting textile threads to the file system would be great to see.

assigning to you @carsonfarmer to lead for this sprint as we really need to nail this down and chat with them this week. happy to help.

**Comment by balupton** [comment]
[Follow up thread.](https://textileio.slack.com/archives/C6V3L4963/p1558500504255200)
