### ISSUE TITLE
Add an `.editorconfig` to each repository

### ISSUE THREAD

**Issue by balupton** [textileio/meta#3]
We should add an `.editorconfig` file to all our projects.

`.editorconfig` files enforce consistent line endings and indentation across user's code editors, linting tools, and auto-formatters, with additional rules for respect the needs of certain languages, such as Markdown which requires 4 spaces, or JSON which requires 2 spaces, or make and python which require tabs.

We can base ours from @Bevry's which defaults to tabs for languages that are agnostic:

- https://github.com/bevry/base/blob/master/.editorconfig

For languages that are indentation agnostic, we need to decide if we want tabs as the default, or if not tabs, then how many spaces. I vote tabs, as it allows everyone to use their preferred indentation, which is more contributor friendly.

Currently, our codebase has a mixture of both spaces and tabs:

- This file uses tabs and 4 spaces: https://github.com/textileio/go-textile/blob/master/docs/docs.go

- This file uses 2 spaces: https://github.com/textileio/desktop/blob/master/src/index.tsx

It would also avoid conflicts such as this, which is due to differing editor configs where there is trimmed whitespace, or a differing line ending.

![Screen Shot 2019-04-24 at 12 46 17 pm](https://user-images.githubusercontent.com/61148/56628922-06af0280-668f-11e9-9246-5b98bbab9440.png)

**Comment by asutula** [comment]
Nice, I like it.

**Comment by balupton** [comment]
Knocked this off on go-textile via https://github.com/textileio/go-textile/pull/703 which uses tabs as that is what the go ecosystem enforces through its own formatters.

For the others, we need confirmation on indentation style, if spaces, how many spaces?

**Comment by balupton** [comment]
From the meeting today, Go will remain in tabs, TypeScript and JavaScript will be set to 2 spaces as per @sanderpick's vote.

Work will commence on this later on in the sprint once people's PR's are merged in, such that conflicts are reduced.

**Comment by balupton** [comment]
@textileio/team 

Please use these for for all future repositories:

https://github.com/textileio/base/blob/master/.editorconfig
https://github.com/textileio/base/blob/master/.gitignore

**Comment by balupton** [comment]
I've published instructions on how to adopt editorconfig at:
https://github.com/textileio/base/blob/master/README.md

**Comment by balupton** [comment]
Removing assignee as with https://github.com/textileio/base/blob/master/README.md we can all do this now.

**Comment by carsonfarmer** [comment]
Closing this and considering it 'done'.
