### ISSUE TITLE
Create a changelog workflow that integrates with our continuous-releases

### ISSUE THREAD

**Issue by balupton** [textileio/meta#32]
A few options for this.

- IPFS Format
- Bevry Format

both output the changelog value into the git tag

Also option is

- Automated format that just dumps the commits, not that helpful though

Need to update the git tag value into the markdown notes for the github release

**Comment by carsonfarmer** [comment]
I think we've established a healthy practice here with 'manual' change logs on releases. See also this work on adding a suggested Release Notes entry with each Pull Request: 
https://github.com/textileio/go-eventstore/blob/master/.github/PULL_REQUEST_TEMPLATE/feature_change.md
We could easily add that .github folder and setup to all existing repos (or any new ones perhaps).

**Comment by carsonfarmer** [comment]
Closing this as stale.
