### ISSUE TITLE
Convert TSLint to ESLint

### ISSUE THREAD

**Issue by balupton** [textileio/meta#35]
TSLint is deprecated now that ESLint supports TypeScript

https://github.com/palantir/tslint/issues/4534

**Comment by balupton** [comment]
I've published instructions on how to do the migration at:
https://github.com/textileio/base/blob/master/README.md

**Comment by balupton** [comment]
Removing assignee as with https://github.com/textileio/base/blob/master/README.md we can all do this now.

**Comment by carsonfarmer** [comment]
Closing this and considering it 'done'. We can create a specific issue on any existing or new 'offending' repos.
