### ISSUE TITLE
Adopt prettier on all repositories

### ISSUE THREAD

**Issue by balupton** [textileio/meta#4]
Prettier.io is a code formatter tool that got widespread adoption last year. It works across many different languages (including javascript, typescript, markdown, json, etc) and supports very advanced human readable formatting out of the box. It does not yet support go, however we already have code formatters for go in our codebase.

The advantage of using such a tool is that our editors will automatically format our code as we type, and it ensures a consistent coding format across languages, repositories, and with the wider programming ecosystem, making adoption easier.

I implemented it across all the @Bevry repos last year, and have been quite pleased with it. It is nice to write code where you just focus on what you want the code to do, and then it formats everything as you type it. Which turned out to be a nice productivity win.

**Comment by balupton** [comment]
This task depends on https://github.com/textileio/meta/issues/3 being done first.

**Comment by balupton** [comment]
@textileio/team 

Please use https://github.com/textileio/base/blob/master/.editorconfig for all future repositories.

**Comment by balupton** [comment]
So I tried this `.prettierignore` for `go-textile:

```
# 2019 May 25
# https://github.com/textileio/base

# ignore anything but the supported extensions
**/*.*
!**/*.mjs
!**/*.js
!**/*.jsx
!**/*.ts
!**/*.tsx
!**/*.json

# ignore dotfiles that don't have an extension
**/.*
!**/.*.*

# ignore common build files
**/docs/
**/dist/
**/vendor/
**/node_modules/
**/*.d.ts
**/testdata/

# ignore ucnommon build files
bin/
android/
ios/
coverage/
release/
.jest/

# ignore files that don't have extensions
CODEOWNERS
test_compile
Dockerfile
LICENSE
Makefile
qa/wallet
```

As an alternative to running on everything and ignoring errors about unsupported files, which is our current technique for go projects.

Our current technique remains better than this verbose and finicky `.prettierignore` style.

[Prettier v2 is under development, and will make this all easier.](https://github.com/prettier/prettier/issues/3503)

**Comment by asutula** [comment]
Do you recommend any editor plugin that allows the "format as you type" think? Or does it just work?

**Comment by balupton** [comment]
> Do you recommend any editor plugin that allows the "format as you type" think? Or does it just work?

See  https://paper.dropbox.com/doc/Coding-Conventions--Ad_Mf~4gqigtAwCBft~9Cwr3Ag-sCiektkUdKjBa2YMEZesp

**Comment by balupton** [comment]
I've published instructions on how to adopt prettier at:
https://github.com/textileio/base/blob/master/README.md

**Comment by balupton** [comment]
Removing assignee as with https://github.com/textileio/base/blob/master/README.md we can all do this now.

**Comment by carsonfarmer** [comment]
Closing this in favor of now just creating issues on any offending _new_ repos?
