### ISSUE TITLE
Deal with lost us-west-1 cafe repo

### ISSUE THREAD

**Issue by sanderpick** [textileio/meta#46]
During a VM resize, the repo was lost. In order to deal with this, I'll need to:
- [x] Finish resizing the data disk
- [x] Cook up a new go lib that has the new peer as bootstrap
- [x] Ensure that you can delete a cafe w/o having to connect to it
- [x] Get the new ID + token into the app
- [x] Have the app somehow display an alert banner if it has a failing cafe?

Too bad we don't have the cluster integration in yet :(

**Comment by sanderpick** [comment]
- Google volume is an acceptable size (500 GiB)
- Azure us-west-1 has been resized to 1023 GiB (by resize I mean create, partition, format, and mount a new smaller disk, copy repo, then finally delete the old one)

**Comment by sanderpick** [comment]
- Azure eu-west-1 has been attached to a smaller disc as well (1023 GiB)

Step-by-step guide is here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/attach-disk-portal

**Comment by sanderpick** [comment]
@asutula for the next release, we'll need to update the suggested cafes to include the new one (the peer ID and token are in the shared vault).

**Comment by sanderpick** [comment]
For this last task, "Have the app somehow display an alert banner if it has a failing cafe?", I'm curious your thoughts there @asutula - this may not be an urgent matter, but something like a basic app-side HTTP request test could work. This could be considered a "connectivity test" that only signals to the user that something is up via a banner or something similar.

**Comment by asutula** [comment]
So, the flow would be... App launches, node starts, ask the node for a list of sessions, grab the cafe.url from each session, and GET or POST to some endpoint on that url? If it fails, display an error banner.

**Comment by sanderpick** [comment]
Yep, for example, just GET https://us-west.cafe.textile.io/cafe 

A second generation connectivity test could run more frequently, but perhaps that should live in the lib and report errors.

**Comment by asutula** [comment]
@sanderpick does this new cafe _replace_ a previous entry?

**Comment by sanderpick** [comment]
Yes - it replaces us-west-1

**Comment by asutula** [comment]
Ok, CI production release build has been updated with the new cafe

**Comment by sanderpick** [comment]
Awesome, thanks.

**Comment by sanderpick** [comment]
The last thing to do here is release the app. We can add a cafe connectivity test later.
