### ISSUE TITLE
Adopt shellcheck for linting all bash/shell scripts

### ISSUE THREAD

**Issue by balupton** [textileio/meta#5]
Just like how we lint other languages as part of our testing, we should also lint with [shellcheck](https://github.com/koalaman/shellcheck) for shell/bash files.

It also has plugins for our various code editors, which is very useful.

**Comment by carsonfarmer** [comment]
Do we still want to have this on our radar @sanderpick? Assigning to you, but feel free to close if no longer a priority.

**Comment by carsonfarmer** [comment]
Closing as stale.
