### ISSUE TITLE
Adopt awesome-travis/surge to deploy repositories to static hosting

### ISSUE THREAD

**Issue by balupton** [textileio/meta#6]
For our CI builds, we can deploy each commit, branch, and tag to a URL using a script like [awesome-travis/surge](https://github.com/bevry/awesome-travis/blob/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/surge.bash).

This enables CDN and docs browsing for each commit, branch, and tag (version). Which could assist in our documentation efforts.

A high level of this functionality can be found at:
https://discuss.bevry.me/t/how-bevry-automates-maintenance-of-its-prolific-open-source-portfolio/693?u=balupton

**Comment by carsonfarmer** [comment]
Still interested in something like Surge for CDN stuff... going to mark for backlog and assign it to myself for further research.

**Comment by carsonfarmer** [comment]
There are simpler ways to go about this. Closing in favour of a simpler approach.
