### ISSUE TITLE
Publish a tutorial-based blog post on using the React Native SDK

### ISSUE THREAD

**Issue by andrewxhill** [textileio/meta#9]
---
name:  React Native SDK blog post

---

## Request

**How would this project demonstrate the Textile technology? What problem does it help solve? Please describe.**

It would be great to see a community written blog post on using the [React Native SDK](https://github.com/textileio/react-native-sdk/). We've just launched the library and people are looking for easy to follow examples to get started using it. Anyone who wants to write on should jump on our developer slack channel (https://slack.textile.io/) to get any help / questions answered along the way. 

We've got a few examples to work from in the wild already including,

* [Textile Photos](https://github.com/textileio/textile-mobile)
* [AirSecure](https://github.com/airsecure/airsecure)
* [Boilerplate](https://github.com/textileio/react-native-boilerplate)

#### Describe the solution you'd like

Ideally, I'd like to see a technical but broadly accessible tutorial on either building an app from scratch or integrating the SDK into an existing app. It should walk through the steps of

1. Node initialization
2. Account creation
3. Thread Creation via a custom schema 
4. Pinning a new file to a Thread
5. Optimally, sharing that Thread with another user/device. 

#### Success 

A successful blog post would be very visual, including screenshots, code examples, maybe even screen recordings / videos of the process. It should go through the steps of using Textile to provide a real service in a running application at the end (some examples include, username + avatar registration, private data management, end to end encrypted sharing). The post would be published on a widely read publication on Medium, or if the approved as a guest post on Textile's blog. Additionally,

* The post will be 500 words or more
* Provide new information not contained on the `react-native-sdk` readme or in the [Textile wiki](https://github.com/textileio/textile-go/wiki)

#### Bounty Selection

In your pre-submission for approval, please provide examples to your previous writing and your plan for dissemination.

**Documentation & Adoption Strategy**

Better if the post could be submitted to a publication with existing readership, but open to individuals writing as well and then we can help share.

** Links that will help **

* [React Native SDK Readme](https://github.com/textileio/react-native-sdk)
* [Textile wiki](https://github.com/textileio/textile-go/wiki)

** Some good examples from our own blog **

[Tutorial: Setting up an IPFS peer, part I](https://medium.com/textileio/tutorial-setting-up-an-ipfs-peer-part-i-de48239d82e0)
[Build a Decentralized Chat App with Knockout and IPFS](https://medium.com/textileio/build-a-decentralized-chat-app-with-knockout-and-ipfs-fccf11e8ce7b)

**Comment by nanspro** [comment]
@andrewxhill  is this bounty up for grabs ?

**Comment by andrewxhill** [comment]
apologies @nanspro just catching this, it had gone stale. i'm going to close this one but we should have new ones in the coming months
